- name: install rolling restart script
  template:
    src: rolling_restart.sh.j2
    dest: /home/centos/rolling_restart.sh

- name: change mode script
  file:
    path: /home/centos/rolling_restart.sh
    mode: 0755

- name: run script
  shell: /home/centos/rolling_restart.sh
  register: elasticsearch_update

##- name: reboot
##  shell: sleep 2 && /usr/sbin/shutdown -r now "Rolling update"
##  #shell: sleep 2 && /usr/sbin/shutdown -h now "Rolling update"
##  async: 1
##  poll: 0
##  ignore_errors: true
##  when: elasticsearch_update.changed
##  changed_when: true
##  register: reboot_after_elasticsearch_update
##
##- name: wait for {{ inventory_hostname }}
##  local_action: wait_for host={{ inventory_hostname }} port=22 state=started delay=8 timeout=3600
##  become: false
##  when: reboot_after_elasticsearch_update.changed
