- name: install rolling restart script
  template:
    src: rolling_restart.sh.j2
    dest: /home/ec2-user/rolling_restart.sh

- name: change mode script
  file:
    path: /home/ec2-user/rolling_restart.sh
    mode: 0755

- name: run script
  shell: /home/ec2-user/rolling_restart.sh
  register: elasticsearch_update

